FROM therecipe/qt:windows_64_static as fcitx
RUN echo "#!/bin/bash" >> /bin/buildwindows
RUN echo "cd /src/ && $GOPATH/bin/qtdeploy build desktop" >> /bin/buildwindows
RUN chmod +x /bin/buildwindows